import { useEffect, useRef, useState } from "react";
import { Link } from "wouter";
import { Mail } from "lucide-react";
import { trackAnalyticsEvent } from "@/lib/analytics";

const EMAILOCTOPUS_FORM_ID = "6084ae70-a563-11f1-a72e-95a7378c618c";
const EMAILOCTOPUS_SCRIPT_URL = `https://eomail5.com/form/${EMAILOCTOPUS_FORM_ID}.js`;
const EMAILOCTOPUS_FALLBACK_URL =
  "https://indianaesportsnetwork.eo.page/nnw3j";
// Match this to the custom Audience field generated by the EmailOctopus form.
const EMAILOCTOPUS_AUDIENCE_FIELD_NAME = "field_3";

const AUDIENCE_OPTIONS = [
  { label: "Coach", value: "Coach" },
  { label: "Community Member", value: "Community Member" },
];

type NewsletterSignupProps = {
  compact?: boolean;
};

function addAudienceField(embed: HTMLDivElement): boolean {
  const form = embed.querySelector<HTMLFormElement>(
    `[data-form="${EMAILOCTOPUS_FORM_ID}"] form`,
  );
  const fieldsContainer = form?.querySelector<HTMLElement>(
    "[eo-form-fields-container]",
  );

  if (
    !form ||
    !fieldsContainer ||
    form.querySelector(`[name="${EMAILOCTOPUS_AUDIENCE_FIELD_NAME}"]`)
  ) {
    return false;
  }

  const fieldset = document.createElement("fieldset");
  fieldset.className =
    "emailoctopus-form-row form-group mb-2 ien-emailoctopus-audience";

  const legend = document.createElement("legend");
  legend.textContent = "I am a";
  fieldset.appendChild(legend);

  const options = document.createElement("div");
  options.className = "ien-emailoctopus-audience-options";

  AUDIENCE_OPTIONS.forEach((option, index) => {
    const label = document.createElement("label");
    label.className = "ien-emailoctopus-audience-option";

    const input = document.createElement("input");
    input.type = "radio";
    input.name = EMAILOCTOPUS_AUDIENCE_FIELD_NAME;
    input.value = option.value;
    input.required = true;
    input.id = `emailoctopus-audience-${index}`;

    const text = document.createElement("span");
    text.textContent = option.label;

    label.append(input, text);
    options.appendChild(label);
  });

  fieldset.appendChild(options);
  fieldsContainer.appendChild(fieldset);

  return true;
}

export default function NewsletterSignup({
  compact = false,
}: NewsletterSignupProps) {
  const embedRef = useRef<HTMLDivElement>(null);
  const [scriptFailed, setScriptFailed] = useState(false);

  useEffect(() => {
    const embed = embedRef.current;
    if (!embed) return;

    setScriptFailed(false);
    embed.innerHTML = "";

    const observer = new MutationObserver(() => {
      if (addAudienceField(embed)) {
        observer.disconnect();
      }
    });

    const script = document.createElement("script");
    script.async = true;
    script.src = EMAILOCTOPUS_SCRIPT_URL;
    script.dataset.form = EMAILOCTOPUS_FORM_ID;
    script.onerror = () => setScriptFailed(true);
    script.onload = () => {
      addAudienceField(embed);
    };

    const handleSuccess = () => {
      trackAnalyticsEvent("stay_connected_submit", {
        source: "emailoctopus_embed",
      });
    };

    document.addEventListener("emailoctopus:form.success", handleSuccess);
    observer.observe(embed, { childList: true, subtree: true });
    embed.appendChild(script);

    return () => {
      observer.disconnect();
      document.removeEventListener("emailoctopus:form.success", handleSuccess);
      embed.innerHTML = "";
    };
  }, []);

  return (
    <div
      id="newsletter"
      className={`relative overflow-hidden rounded-xl border border-primary/25 bg-card shadow-[0_0_30px_rgba(212,175,55,0.08)] ${
        compact ? "h-full" : "max-w-5xl mx-auto"
      }`}
    >
      <div className="absolute inset-0 bg-[linear-gradient(rgba(212,175,55,0.08)_1px,transparent_1px),linear-gradient(90deg,rgba(212,175,55,0.08)_1px,transparent_1px)] bg-[size:44px_44px] opacity-35" />
      <div
        className={
          compact
            ? "relative flex h-full flex-col gap-6 p-6"
            : "relative grid gap-8 p-6 md:grid-cols-[0.85fr_1fr] md:p-10"
        }
      >
        <div
          className={
            compact
              ? "flex flex-col justify-center text-left"
              : "flex flex-col justify-center text-center md:text-left"
          }
        >
          <div
            className={`mb-4 flex h-12 w-12 items-center justify-center rounded-full border border-primary/35 bg-background text-primary ${
              compact ? "" : "mx-auto md:mx-0"
            }`}
          >
            <Mail className="h-5 w-5" aria-hidden="true" />
          </div>
          <p className="mb-3 font-heading text-xs font-bold uppercase tracking-[0.2em] text-primary">
            Stay Connected
          </p>
          <h2
            className={`mb-4 font-heading font-bold uppercase text-white ${
              compact ? "text-2xl md:text-3xl" : "text-3xl md:text-4xl"
            }`}
          >
            Get IEN Updates
          </h2>
          <p className="text-sm leading-6 text-muted-foreground md:text-base">
            Subscribe for league announcements, event information, coach
            reminders, and statewide Indiana esports news.
          </p>
          <p className="mt-4 text-xs leading-5 text-muted-foreground/75">
            This does not register or charter a school for competition.
          </p>
        </div>

        <div className="rounded-lg border border-primary/15 bg-background/70 p-4 md:p-5">
          <div ref={embedRef} className="ien-emailoctopus-embed min-h-[16rem]">
            <p className="py-12 text-center text-sm text-muted-foreground">
              Loading signup form...
            </p>
          </div>
          {scriptFailed && (
            <p className="mt-4 text-center text-sm text-muted-foreground">
              Having trouble loading the form?{" "}
              <a
                href={EMAILOCTOPUS_FALLBACK_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="font-heading font-bold uppercase text-primary hover:text-yellow-200"
              >
                Open the signup page
              </a>
              .
            </p>
          )}
        </div>
      </div>
      <p className="relative border-t border-primary/10 px-6 py-4 text-center text-xs text-muted-foreground">
        Looking to start or renew a school program?{" "}
        <Link
          href="/schools#school-participation"
          className="font-heading font-bold uppercase tracking-[0.14em] text-primary hover:text-yellow-200"
        >
          Visit Member Schools
        </Link>
        .
      </p>
    </div>
  );
}
